---
- name: Configure Yum Repository If CentOS 6 Or 7
  yum: name=http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Configure Yum Repository If CentOS 7
  yum: name=http://repo.zabbix.com/zabbix/2.2/rhel/7/x86_64/zabbix-release-2.2-1.el7.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"


- name: Install Zabbix Server with PgSQL
  yum: pkg={{item}} state=present
  with_items:
   - zabbix-server-pgsql
   - zabbix-web-pgsql
   - zabbix-agent
   - zabbix-java-gateway


# Task Description
#------------------------------
# Step-3: Zabbix Installation
#-----------------------------
